init 1 python:
    music_list_7dl = {
        "Denis Stelmakh - Afraid of Destiny": _7DL.music("afraid_of_destiny"),
        u"С. Ейбог feat. Liru - Everlasting Summer (cut 1)": _7DL.music("alice_theme"),
        "Josh Powell - Anglegrinder": _7DL.music("anglegrinder"),
        "I am waiting for you last summer - Surrender": _7DL.music("are_you_there"),
        "Josh Powell - Creeping up": _7DL.music("areyouabully"),
        "Christina Perri - A Thousand years (Piano-Cello ThePianoGuys Cover)": _7DL.music("ask_you_out"),

        "Touhou - Bad Apple (Receptor Cover)": _7DL.music("bad_apple"),
        "Josh Powell - Beat Symphonic": _7DL.music("beat_symphonic"),
        "Porter Robinson - Fellow Feeling (no drop edit)": _7DL.music("beasteye"),
        "Olafur Arnalds - Beth Theme": _7DL.music("beth"),
        "Clint Mansell - Together We Will Live Forever (Guitar Cover)": _7DL.music("breath_again"),
        "Sia - Breathe Me": _7DL.music("breath_me"),
        "Funczion Sounds - Heretics and Dreamers": _7DL.music("but_why"),

        "Kari Sigurdsson - Trailer Cat": _7DL.music("catch_the_hedge"),
        "James Dooley - The story of You and Me": _7DL.music("christmas_met"),
        "V-Flower - Close to you (Guitar Cover by Justin Ly)": _7DL.music("closetoyou"),
        "RealFaction - A forgotten past": _7DL.music("clueless_hope"),

        "Yurima - Kiss The rain (Acoustic Cover)": _7DL.music("dance_with_me"),
        "Yurima - Kiss The Rain": _7DL.music("dance_with_me_piano"),
        "Seether – Careless Whisper (George Michael сover)": _7DL.music("danceagain"),
        "Charlie Clouser - Dead Silence": _7DL.music("dead_silence"),
        "April Rain - Deadman on vacation": _7DL.music("deadman"),
        "Funczion Sounds - Deep Insude (CrossChannel OST)": _7DL.music("deep_inside"),
        "Emika - Drop the other(instrumental)": _7DL.music("dropit"),
        u"Алексей Омельчук - Гитарный трек 11": _7DL.music("dv_guitar"),

        u"Владимир Зеленцов - Emptiness": _7DL.music("emptiness"),
        u"С. Ейбог feat. Liru - Everlasting Summer (cut 2)": _7DL.music("es_downmix"),
        "Josh Kramer (feat. Tina Guo) - Where The Light Goes": _7DL.music("escape_2"),
        u"С. Ейбог feat. Liru - Everlasting Summer": _7DL.music("everlasting_summer_alice"),
        "April Rain – Exodus": _7DL.music("exodus"),

        "Stefano Mocini - Inside": _7DL.music("feel_you_inside"),
        "ATB – Trilogy (The Final Chapter)": _7DL.music("finale_farewell"),
        "MilkMan-DanAnother Once Ago": _7DL.music("forgive_or_what"),
        "Jorge Mendez - Cold": _7DL.music("frostwithoutyou"),
        "Tim Nyman - Full Scale Loneliness": _7DL.music("fsl_tn"),

        "Funczion Sounds - Slapstick": _7DL.music("genki"),
        "DeepCosmo - Submarine": _7DL.music("gonna_be_ok"),
        "Akaaka - Makkakka": _7DL.music("groovie"),
        "Beat Bites - Forensic Science": _7DL.music("guitar_under_the_window"),

        "James Dooley - Happy Endings": _7DL.music("happy_ending"),
        "Jack Wall - Humans Are Disappearing": _7DL.music("herc_death"),

        "Josh Powel - Resolution": _7DL.music("iamagod2"),
        "Michael Ortega - Sad Piano For a Broken Heart": _7DL.music("iamsadiamsorry"),
        "Ainset - Romantic score (inakrin's mix)": _7DL.music("iamsadiamsorry2"),
        "I am waiting for you last summer - Neon fever": _7DL.music("iamsadiamsorry3"),
        "Olafur arnalds – So Close (feat. Arnor Dan) 2": _7DL.music("intro2"),
        "Olafur arnalds – So Close (feat. Arnor Dan) 1": _7DL.music("intro1"),
        u"Ганджу - I want magic": _7DL.music("iwantmagic"),

        "Eels - I Need Some Sleep (Piano Cover)": _7DL.music("kiss_you"),
        "Digital Elvis & Zero – Theme from the Ocean (OST Достучаться до небес)": _7DL.music("knock"),

        "ALyosha - Sweet People караоке (минус) (cut)": _7DL.music("last_pixie"),
        "Hatsune Miku feat. Kz (LiveTune) - Last Night Good Night Guitar Cover": _7DL.music("lastlight_guitar"),
        "Hatsune Miku - Last Night Good Night (Piano Cover by Lee Keng Tat)": _7DL.music("lastlight_piano"),
        "Arn Andersson - Annihilation": _7DL.music("laugh_throught_the_universe"),
        "Funczion Sounds - We became friends!": _7DL.music("lazy_olga"),
        u"Евгений Крылатов - Лиловый Шар (Metal Cover)": _7DL.music("liliac_ball"),
        "Beat Bites - Programming Victory": _7DL.music("loki_on_3"),
        "James Last - Lonesome Shepherd": _7DL.music("lonesome_shepherd"),
        "Audiomachine - Longing": _7DL.music("longing"),
        "Bosa - Fun Teacher": _7DL.music("there_you_are"),
        "Bosa - The popular kids": _7DL.music("lost_without_you"),
        "Roxette - Listen To Your Heart (Acousctic Cover by Igor Presnyakov)": _7DL.music("ltyh"),
        "Rengoku Teien - Boku wa boku janai bokudeatte boku janai (2nd Edition)": _7DL.music("lullaby2"),
        "Л. ван Бетховен - Лунная Соната (ремикс)": _7DL.music("lunar_anguish"),
        "Olafur Arnalds - Lynn theme": _7DL.music("lynn"),
        u"Сектор Газа - Лирика": _7DL.music("lyrica_sg"),

        "Bloodhound Gang - The Bad Touch": _7DL.music("mammal"),
        "Jack Wall - Suicide Mission": _7DL.music("me2ost"),
        "For The Stars - Meet Me There(Silent Owl Cover)": _7DL.music("meetmethere_tts"),
        "Marcus D - Kindred Spirit": _7DL.music("melancholy_sun"),
        u"Алексей Омельчук - Надежда": _7DL.music("misery"),
        u"Олег Анофриев - Есть Только Миг (OST «Земля Санникова»)": _7DL.music("moment"),
        "Tom Day - Our World": _7DL.music("more_than_alive"),
        "Mark Morgan - My Chrysalis Higwayman": _7DL.music("my_chrysalis_highwayman"),
        "Kristofferson - Where do tears go": _7DL.music("my_only_hope"),

        "Jassummisko - Bassment Pianist": _7DL.music("no_hope_left"),
        "Limp Bizkit - Nookie": _7DL.music("nookie"),
        "Stefano Mocini - Life": _7DL.music("nowyouseeme"),

        "Yiruma – River Flows in You (Cello & Piano)": _7DL.music("old_kiss"),
        "DeVso - When I First Met You": _7DL.music("ourfirstmet"),
        "Jessica Curry - Twenty One": _7DL.music("out_of_painkillers"),
        u"Ясухара Таканаси - Eau de Vie (Shiki OST)": _7DL.music("out_of_your_tier"),
        "IA - Outer Science": _7DL.music("outer"),

        "Micheal Ortega - Night of rain": _7DL.music("pathways"),
        "Sonic Librarian - Firefly Mist": _7DL.music("pixies_playing"),
        "Slava Jamm feat. Please Reprise - WTCS11": _7DL.music("please_reprise"),
        "KPM Music - Bass Renaissaince 1": _7DL.music("polyhymnia_intro"),
        "KPM Music - Bass Renaissaince 2": _7DL.music("polyhymnia_main"),
        "PPK - Resurrection": _7DL.music("ppk"),
        "Marilyn Manson - Coma White (Acoustic Cover)": _7DL.music("prologue_1"),
        "Marilyn Manson - Coma White (DeadPunk Cover)": _7DL.music("prologue_2"),
        "Arn Andersson & Nights Amore - Farewell Life": _7DL.music("promise_to_meet_you"),

        "Sergey Eybog – Raindrops": _7DL.sfx("raindrops_radio"),
        "Qrown - Gokagetu": _7DL.music("red_lights"),
        "Mitchell Broom – Redemption": _7DL.music("redemption"),
        "Moonlight - Electric Cello (Inspired by Beethoven) - The Piano Guys": _7DL.music("refuse_to_believe"),
        "Oi Va Voi - Yesterday's Mistakes": _7DL.music("refuse_to_replay"),
        "KPM Music - Change Times": _7DL.music("rewind"),
        "Jan Cyrka - The Right Road": _7DL.music("rightroad"),
        "Heavenly - The Ritual": _7DL.music("ritual2"),
        "The Neighbourhood - Sweater Weather (Instrumental)": _7DL.music("runaway"),

        "Olexandr Ignatov - Sad Piano": _7DL.music("sad_piano"),
        "19's Sound Factory - Dear (Music Box Cover)": _7DL.music("sam_lullaby"),
        "Scorpions - Still Loving You (Cover by Kfir Ochaion)": _7DL.music("scorpions"),
        "Purgatory Bunny - Light Chain": _7DL.music("semische"),
        "April Rain – 7 дней лета (7ДЛ OST)": _7DL.music("seven_summer_days"),
        u"DeepCosmo - День космонавтики": _7DL.music("sh_ai_rejuv"),
        "Sting - Shape of my heart (instrumental)": _7DL.music("shape_of_my_heart"),
        "KPM Music - She has gone": _7DL.music("shehasgone"),
        "Ellie Goulding - Stay Awake (Guitar Cover by Igor Silchenko)": _7DL.music("sheiscool"),
        "3L - Kōrui ni shi dzumu wa tomobito no urei (Remix)": _7DL.music("shib_mono"),
        "3L - Kōrui ni shi dzumu wa tomobito no urei": _7DL.music("shib_stereo"),
        "OST Amnesia Ukyo Melody (Rock)": _7DL.music("sign_of_blood"),
        "April Rain - My silent angel": _7DL.music("silent_angel"),
        "Buoy - ==(Time Lapse of Clouds)==": _7DL.music("sky_feather"),
        "Gothic Storm - We meet in dreams": _7DL.music("slavyas_fantazm"),
        "Beat Bites - Ghoulish Chemistry": _7DL.music("sneakupon"),
        "DeepCosmo - Тихо (Acoustic)": _7DL.music("so_cold"),
        "Ólafur Arnalds - Raein": _7DL.music("so_lonely"),
        "Adele - Someone Like You(Sungha Jung Cover)": _7DL.music("someone_like_you_guitar"),
        u"Сплин - Романс": _7DL.music("splin"),
        "Scorpions - Still Loving You (Cover by Ozielzinho)": _7DL.music("stilllovingyou"),
        u"Кино - Кончится Лето (Guitar Cover)": _7DL.music("summer_ends_soon2"),

        "Funczion Sounds - To the world of dreams": _7DL.music("take_my_hand"),
        u"Акира Ямаока - Tears of pain (Silent Hill OST)": _7DL.music("tears_of"),
        "Hatsune Miku feat. Kz (Livetune) - Tell Your World (Acoustic Cover)": _7DL.music("tellyourworld"),
        "DeepCosmo - DVATRI": _7DL.music("temptation"),
        "Camelia - Splatter Party (feat. Hatsune Miku)": _7DL.music("tender_song"),
        "Zack Hamsey - The way": _7DL.music("the_way"),
        "Hans Zimmer - Rain Man Theme": _7DL.music("thousand_little_things"),
        "ALyosha - Sweet People караоке (минус)": _7DL.music("thousand_of_pixies"),
        "April Rain - Exploring yourself with a knife": _7DL.music("tilltheend"),
        "Tim McMorris - Translation (Inspirational One)": _7DL.music("timetowakeup"),
        u"Владимир Розанов - С запада на восток": _7DL.music("to_the_sunrise"),
        "Broove - |oove|Heartbeats": _7DL.music("too_quiet"),

        "Vflower - Close to you (feat. Justin Ly)": _7DL.music("uncertainity"),
        "April Rain - Violent Passion Surrogate": _7DL.music("uneven_me"),
        "Audiomachine - Unfinished Life": _7DL.music("unfinished_life"),
        "Martin O'Donnel - Unforgotten": _7DL.music("unforgotten"),
        "April Rain – Мы будем жить (7ДЛ OST)": _7DL.music("unfulfilled"),
        "The Ring OST - Samara's Song (Piano Cover)": _7DL.music("unholy_you"),

        "Mattashi - Together": _7DL.music("vale"),
        "Marilyn Manson - If I could be your vampire": _7DL.music("vampire"),

        "DeadPunk - Regret": _7DL.music("regret"),
        "Limp Bizkit - Walking Away": _7DL.music("walking_away"),
        "Kaivaan ft. Hikaru Station - Escape (Acoustic guitar cover)": _7DL.music("what_am_i_doing_here"),
        "DeVso - DeVso-Music-The Avengers": _7DL.music("what_cost"),
        "Curse - Und was ist jetzt (Instrumental)": _7DL.music("whatnow"),
        "Funczion Sounds - Taking hand in hand": _7DL.music("wheres_wonderland"),
        "Olafur Arnalds - Near Light": _7DL.music("will_you"),
        u"Евгений Крылатов - Гостья из будущего OST": _7DL.music("wonderful_faraway"),

        "Kabaneri of the Iron Fortress (Fingerstyle Guitar Cover)": _7DL.music("you_are_human"),
        "Kabaneri of the Iron Fortress (Piano Cover)": _7DL.music("you_are_soul"),
        "Ninelie Kabaneri of the Iron Fortress Ending Orchestral Cover Mike Reed IX": _7DL.music("you_are_star"),
        "Michael John Gordon - The end (Wolfenstein The Old Blood OST)": _7DL.music("you_were_late"),
        "Kári Sigurðsson - Stay": _7DL.music("youareours"),
        "Tom Day - Going Home": _7DL.music("your_life"),
        "Ólafur Arnalds - This Place Was A Shelter": _7DL.music("youre_not_real"),

#0.34.а
        "Olafur Arnalds - Brim": _7DL.music("brim"),
        "Kevin MacLeod - Quirky Dog": _7DL.music("bureaucracy"),
        "Pachebel - Canon D (flamenco ver)": _7DL.music("canon_d_flamenco"),
        "Kevin MacLeod - Carefree": _7DL.music("carefree"),
        "Matt Quentin - Waves": _7DL.music("everyday"),
        "Olafur Arnalds - Fyrsta": _7DL.music("fyrsta"),
        "Hungarian Dances No 5 J Brahms - Passepartout Piano Duo": _7DL.music("hdance_5"),
        "Potsu x Lando! - Breakfast": _7DL.music("hug_me_already"),
        "Joakim Karud - Dreams": _7DL.music("imfine"),
        "Kevin MacLeod - Gymnopedie No 1": _7DL.music("midday_reverie"),
        "Ólafur Arnalds - 1440": _7DL.music("nap_one"),
        "Just Big Hills - Shinjuku": _7DL.music("one_little_lone_cloud"),
        "DeadPunk - 7dl intro (7ДЛ OST)": _7DL.music("sammy"),
        "Kevin MacLeod - Your Call High Quality": _7DL.music("shappihn"),
        "Orca Vibes - Gypsy": _7DL.music("shestheone"),
        "DeadPunk - 7dl melody2 (7ДЛ OST)": _7DL.music("snatch"),
        "Slot - Круги на воде (instrumental)": _7DL.music("so_be_it"),
        "SURF - Take Care": _7DL.music("surf"),
        "Mattdeguia - Daylight": _7DL.music("too_serious"),
#0.34.b
        "DeadPunk - Hell": _7DL.music("hell"),
        "Steezy Prime - Explore": _7DL.music("explore"),
        "ППВК - Последнее лето": _7DL.music("last_summer"),
        "ППВК - Волшебство уходит": _7DL.music("magic_is_gone"),
        "Matt Quentin - Morning Dew": _7DL.music("morning_dew"),
        "DeadPunk - PleaseStopIt": _7DL.music("please_stop_it_mastered"),
        "Kazam - Raindrops": _7DL.music("raindrops"),
        "DeadPunk - Vibe": _7DL.music("vibe"),
#0.35.a
        "Clint Mansell - Together We Will Live Forever (Guitar Cover)": _7DL.music("breath_again_slow"),
        "Beat Bites - Game of Shadows": _7DL.music("game_of_shadows"),
        "Beat Bites - Last Train Home": _7DL.music("lth"),
        "Olafur Arnalds - Not Alone": _7DL.music("not_alone"),
        "Kevin MacLeod - Your Call High Quality": _7DL.music("shappihn"),
        "April Rain - Im All Crying Inside": _7DL.music("tearing_sobs"),
        "My Royal Guardian - Yume Akari": _7DL.music("yume_akari"),
        "Kevin MacLeod - Niles Blues": _7DL.music("viola"),
        "Аревик Аветисян – Воспоминание": _7DL.music("sorrow"),
        "DeadPunk - Smells Like My Grave": _7DL.music("smlg"),
#0.36.a
        "Julian Kruse - Fallen From The Sky": _7DL.music("think_again"),
        "AOA - Miniskirt": _7DL.music("you_re_dam_funny"),
        "PianoPrinceOfAnime - Always Watching Over You (Violet Evergarden OST)": _7DL.music("gimme_hand"),
        "Tracey Chattaway - Love is Here": _7DL.music("hear_a_love"),
        "Fabrizio Paterlini - Week #12": _7DL.music("what_if"),
#0.37.a
        "Apocalyptica - Faraway": _7DL.music("faraway"),
        "Secret Garden - Hymn to Hope": _7DL.music("last_hope"),
        "Poets of the Fall - Carnival of Rust": _7DL.music("ofrust"),
        "Hinkik - Time Leaper": _7DL.music("pure_energy"),
        "Acid Jazz vs. Drum'n'Bass - Jungle Radio": _7DL.music("radio_void"),
        "Кино - Кончится Лето": _7DL.music("summer_ends_soon"),
        "Portishead - Roads (Instrumental Cover)": _7DL.music("war_to_fight"),
        "DeadPunk - Alone": _7DL.music("alone"),
        "DeadPunk - SaveMe": _7DL.music("saveme"),
        "Nicolai Heidlas - Letting Go": _7DL.music("let_me_down"),
        "Natureworld1986 - Underworld": _7DL.music("abyss_call"),
        "Arn Andersson - Aftermath": _7DL.music("aftermath"),
        "Arn Andersson - Annihilation (new version)": _7DL.music("devastated"),
        "Arn Andersson - Childhood Memories (The First Era 2014)": _7DL.music("keep_looking"),
        "Arn Andersson - Dawn": _7DL.music("dawn"),
        "Arn Andersson - The Veil": _7DL.music("brigh_you"),
        "Arn Andersson & Eli Richardson - Everlasting": _7DL.music("i_will_find_you"),
#0.38.a
        "Linkin Park - Crawling (Cello Cover) w/ Krwlng Intro": _7DL.music("krwling"),
        "Oasis - Stop Crying Your Heart Out (Acoustic Cover)": _7DL.music("see_one_day"),
#0.40
        "Kevin MacLeod - Comfortable Mystery 3": _7DL.music("comfortable_mistery_3"),
        "Kevin MacLeod - Comfortable Mystery 4": _7DL.music("comfortable_mistery_4"),
        "Sopor Aeternus & The Ensemble Shadows - Abschied": _7DL.music("requiem"),
        "Balmorhea - Remembrance": _7DL.music("hole_in_chest"),
        "Frames - Don't Stay Here": _7DL.music("leave_now"),
        "SinkWay - 7dl noir (7ДЛ OST)": _7DL.music("noir_ending"),
        "Bob Bradley & Thomas Balmforth - Embers Glow": _7DL.music("embers"),
#0.41
        "Sergey Eybog - UVAO 2": _7DL.music("uvao2"),
        "Лирика - Сектор Газа (Гитара Классика Фингерстайл)": _7DL.music("lyrics"),
        "Kaai Yuki - Ikanaide": _7DL.music("ikanaide"),
        "Bob Bradley & Thomas Balmforth & Chris Egan - Moment Of Reflection": _7DL.music("reflection"),
        "Sergey Eybog - Let's Be Friends (Cover by Dmitry Yakovlev)": _7DL.music("lets_be_friends"),
    }